apiVersion: v1
kind: ConfigMap
metadata:
  name: fast-api-be-config
  namespace: default
data:
  ENVIRONMENT: DEV
  DEBUG: "True"

  BACKEND_SERVER_HOST: "0.0.0.0"
  BACKEND_SERVER_PORT: "8000"
  BACKEND_SERVER_WORKERS: "1"

  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_SCHEMA: postgresql

  IS_ALLOWED_CREDENTIALS: "True"

  DB_TIMEOUT: "5"
  DB_POOL_SIZE: "100"
  DB_MAX_POOL_CON: "80"
  DB_POOL_OVERFLOW: "20"
  IS_DB_ECHO_LOG: "True"
  IS_DB_EXPIRE_ON_COMMIT: "False"
  IS_DB_FORCE_ROLLBACK: "True"

  JWT_ALGORITHM: HS256
  JWT_MIN: "60"
  JWT_HOUR: "23"
  JWT_DAY: "6"

  HASHING_ALGORITHM_LAYER_1: bcrypt
  HASHING_ALGORITHM_LAYER_2: argon2