apiVersion: v1
kind: Secret
metadata:
  name: fast-api-be-secret
  namespace: default
type: Opaque
stringData:
  # Must match k8s/postgres.yml exactly
  POSTGRES_DB: account_db
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres

  API_TOKEN: f8579b46-07d9-4474-8920-c5ded70f7dfb
  AUTH_TOKEN: 4093e574-3f82-41d4-9cd8-58ae233e6216

  JWT_SECRET_KEY: 7dbfb7ef-1858-4382-acad-e657631e7e81
  JWT_SUBJECT: 5ac19d0b-2a69-461f-8811-cd7a22db48a8
  JWT_TOKEN_PREFIX: b738b8b7-d66a-4e99-ae4a-f9eaff6df7c7

  HASHING_SALT: change-this-for-learning